# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# finalProject.py
# Created on: 2016-04-24 17:27:32.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# Clip bear nuisances to area,  find the mean circle
# ---------------------------------------------------------------------------

# import system module
import sys
# Import arcpy module
import arcpy
#import numpy

# import BearNuisance functions
import BearNuisance

# Set Geoprocessing environments
arcpy.env.workspace = "C:\\Users\\mdeeds\\Documents\\Mayer\\FRCC\\GIS210_Intermediate\\FinalProject\\BearNuisance.gdb"

# enable overwriting
arcpy.env.overwriteOutput = True

# Local variables:
# The merged 5 county parcel data
countyParcelsMerge = "countyParcelsMerge"
# Merged parcel data with Single Family Houses selected
countyParcelsMerge_Houses = "countyParcelsMerge_Select"
# Housing Parcel Layer
countyParcelsMerge_Houses_Layer = "countyParcelsMerge_Houses_Layer"

#BearKD_reclass_poly = "BearKD_reclass_poly"

# housesFC = "countyParcelsMerge_Select"
# bearFC = "BearKD_reclass_poly"

try :

    # Don't select houses if the data already exists (this select is slow)
    if (not (arcpy.Exists(countyParcelsMerge_Houses)) ) :
        # Select Single House parcels from County Merge data
        # Process: Select
        arcpy.Select_analysis(countyParcelsMerge, countyParcelsMerge_Houses, "DESCRIPT = 'SINGLE FAMILY'")

    # Make a feature layer from Housing Parcels
    ## Process: Make Feature Layer
    # MakeFeatureLayer_management (in_features, out_layer, {where_clause}, {workspace}, {field_info})
    arcpy.MakeFeatureLayer_management(countyParcelsMerge_Houses, countyParcelsMerge_Houses_Layer)

except arcpy.ExecuteError :
    print arcpy.GetMessages(2)
    sys.exit(1)

except Exception, err:
    sys.stderr.write('ERROR: %s' % str(err))
    sys.exit(1)

# Make Bear Nuisance Density : 4 tiers
BearNuisance.MakeDensityTiers()

# Find parcels that intersect each tier
BearNuisance.IntersectTierParcels()
